// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/admin.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "admin";

export interface Empty {
}

export interface Post {
  id: number;
  title: string;
  url_anh: string;
  content: string;
  editor_id: number;
  editor_realname: string;
  status: string;
  create_at: string;
  update_at: string;
}

export interface CreatePostRequest {
  title: string;
  url_anh: string;
  content: string;
  editor_id: number;
  editor_realname: string;
}

export interface GetPostByIdRequest {
  id: number;
}

export interface UpdatePostRequest {
  id: number;
  title: string;
  url_anh: string;
  content: string;
}

export interface DeletePostRequest {
  id: number;
}

export interface UpdatePostStatusRequest {
  id: number;
}

export interface GetPostsByEditorRequest {
  editor_id: number;
}

export interface PostResponse {
  post: Post | undefined;
}

export interface ListPostResponse {
  posts: Post[];
}

export interface Withdraw {
  id: number;
  user_id: number;
  amount: number;
  bank_name: string;
  bank_number: string;
  bank_owner: string;
  /** PENDING, SUCCESS, ERROR */
  status: string;
  /** ai duyệt */
  finance_id: number;
  request_at: string;
  success_at: string;
}

export interface CreateWithdrawRequestt {
  user_id: number;
  amount: number;
  bank_name: string;
  bank_number: string;
  bank_owner: string;
}

export interface GetWithdrawsByUserRequest {
  user_id: number;
}

export interface UpdateWithdrawStatusRequest {
  /** id của yêu cầu rút */
  id: number;
  /** id admin duyệt */
  finance_id: number;
  /** SUCCESS hoặc ERROR */
  status: string;
}

export interface WithdrawResponse {
  withdraw: Withdraw | undefined;
}

export interface ListWithdrawResponse {
  withdraws: Withdraw[];
}

export interface Finance {
  id: number;
  user_id: number;
  /** NAP hoặc RUT */
  type: string;
  amount: number;
  create_at: string;
}

export interface CreateFinanceRequest {
  user_id: number;
  /** NAP hoặc RUT */
  type: string;
  amount: number;
}

export interface GetFinanceByUserRequest {
  user_id: number;
}

export interface FinanceResponse {
  finance: Finance | undefined;
}

export interface ListFinanceResponse {
  finances: Finance[];
}

export interface FinanceSummaryResponse {
  total_nap: number;
  total_rut: number;
  /** tổng nạp - tổng rút */
  balance: number;
}

export interface AccountSell {
  id: number;
  username: string;
  password: string;
  url: string;
  description: string;
  price: number;
  /** ACTIVE hoặc SOLD */
  status: string;
  partner_id: number;
  createdAt: string;
}

export interface CreateAccountSellRequest {
  username: string;
  password: string;
  url: string;
  description: string;
  price: number;
  partner_id: number;
}

export interface UpdateAccountSellRequest {
  id: number;
  url: string;
  description: string;
  price: number;
}

export interface DeleteAccountSellRequest {
  id: number;
}

export interface GetAccountsByPartnerRequest {
  partner_id: number;
}

export interface GetAccountByIdRequest {
  id: number;
}

export interface UpdateAccountStatusRequest {
  id: number;
  /** SOLD hoặc ACTIVE */
  status: string;
}

export interface AccountSellResponse {
  account: AccountSell | undefined;
}

export interface ListAccountSellResponse {
  accounts: AccountSell[];
}

export const ADMIN_PACKAGE_NAME = "admin";

/** ===== SERVICE DEFINITION ===== */

export interface EditorServiceClient {
  /** Cho role Editor */

  createPost(request: CreatePostRequest, metadata?: Metadata): Observable<PostResponse>;

  getAllPosts(request: Empty, metadata?: Metadata): Observable<ListPostResponse>;

  getPostById(request: GetPostByIdRequest, metadata?: Metadata): Observable<PostResponse>;

  updatePost(request: UpdatePostRequest, metadata?: Metadata): Observable<PostResponse>;

  deletePost(request: DeletePostRequest, metadata?: Metadata): Observable<PostResponse>;

  lockPost(request: UpdatePostStatusRequest, metadata?: Metadata): Observable<PostResponse>;

  unlockPost(request: UpdatePostStatusRequest, metadata?: Metadata): Observable<PostResponse>;

  getPostsByEditor(request: GetPostsByEditorRequest, metadata?: Metadata): Observable<ListPostResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface EditorServiceController {
  /** Cho role Editor */

  createPost(request: CreatePostRequest, metadata?: Metadata): Observable<PostResponse>;

  getAllPosts(request: Empty, metadata?: Metadata): Observable<ListPostResponse>;

  getPostById(request: GetPostByIdRequest, metadata?: Metadata): Observable<PostResponse>;

  updatePost(request: UpdatePostRequest, metadata?: Metadata): Observable<PostResponse>;

  deletePost(request: DeletePostRequest, metadata?: Metadata): Observable<PostResponse>;

  lockPost(request: UpdatePostStatusRequest, metadata?: Metadata): Observable<PostResponse>;

  unlockPost(request: UpdatePostStatusRequest, metadata?: Metadata): Observable<PostResponse>;

  getPostsByEditor(request: GetPostsByEditorRequest, metadata?: Metadata): Observable<ListPostResponse>;
}

export function EditorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createPost",
      "getAllPosts",
      "getPostById",
      "updatePost",
      "deletePost",
      "lockPost",
      "unlockPost",
      "getPostsByEditor",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EditorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EditorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const EDITOR_SERVICE_NAME = "EditorService";

/** ===== SERVICE DEFINITION ===== */

export interface CashierServiceClient {
  /** Người dùng gửi yêu cầu rút tiền */

  createWithdrawRequest(request: CreateWithdrawRequestt, metadata?: Metadata): Observable<WithdrawResponse>;

  /** Người dùng xem lịch sử rút tiền */

  getWithdrawsByUser(request: GetWithdrawsByUserRequest, metadata?: Metadata): Observable<ListWithdrawResponse>;

  /** Admin xem tất cả yêu cầu rút tiền */

  getAllWithdrawRequests(request: Empty, metadata?: Metadata): Observable<ListWithdrawResponse>;

  /** Admin duyệt yêu cầu rút tiền */

  approveWithdraw(request: UpdateWithdrawStatusRequest, metadata?: Metadata): Observable<WithdrawResponse>;

  /** Admin từ chối (lỗi giao dịch, thông tin sai, ...) */

  rejectWithdraw(request: UpdateWithdrawStatusRequest, metadata?: Metadata): Observable<WithdrawResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface CashierServiceController {
  /** Người dùng gửi yêu cầu rút tiền */

  createWithdrawRequest(request: CreateWithdrawRequestt, metadata?: Metadata): Observable<WithdrawResponse>;

  /** Người dùng xem lịch sử rút tiền */

  getWithdrawsByUser(request: GetWithdrawsByUserRequest, metadata?: Metadata): Observable<ListWithdrawResponse>;

  /** Admin xem tất cả yêu cầu rút tiền */

  getAllWithdrawRequests(request: Empty, metadata?: Metadata): Observable<ListWithdrawResponse>;

  /** Admin duyệt yêu cầu rút tiền */

  approveWithdraw(request: UpdateWithdrawStatusRequest, metadata?: Metadata): Observable<WithdrawResponse>;

  /** Admin từ chối (lỗi giao dịch, thông tin sai, ...) */

  rejectWithdraw(request: UpdateWithdrawStatusRequest, metadata?: Metadata): Observable<WithdrawResponse>;
}

export function CashierServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createWithdrawRequest",
      "getWithdrawsByUser",
      "getAllWithdrawRequests",
      "approveWithdraw",
      "rejectWithdraw",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CashierService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CashierService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CASHIER_SERVICE_NAME = "CashierService";

/** ===== SERVICE DEFINITION ===== */

export interface FinanceServiceClient {
  /** Khi nạp/rút thành công, ghi lại dòng tiền */

  createFinanceRecord(request: CreateFinanceRequest, metadata?: Metadata): Observable<FinanceResponse>;

  /** Lấy danh sách giao dịch của 1 user */

  getFinanceByUser(request: GetFinanceByUserRequest, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Lấy tất cả giao dịch (cho admin) */

  getAllFinance(request: Empty, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Thống kê tổng nạp và tổng rút */

  getFinanceSummary(request: Empty, metadata?: Metadata): Observable<FinanceSummaryResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface FinanceServiceController {
  /** Khi nạp/rút thành công, ghi lại dòng tiền */

  createFinanceRecord(request: CreateFinanceRequest, metadata?: Metadata): Observable<FinanceResponse>;

  /** Lấy danh sách giao dịch của 1 user */

  getFinanceByUser(request: GetFinanceByUserRequest, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Lấy tất cả giao dịch (cho admin) */

  getAllFinance(request: Empty, metadata?: Metadata): Observable<ListFinanceResponse>;

  /** Thống kê tổng nạp và tổng rút */

  getFinanceSummary(request: Empty, metadata?: Metadata): Observable<FinanceSummaryResponse>;
}

export function FinanceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createFinanceRecord", "getFinanceByUser", "getAllFinance", "getFinanceSummary"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FinanceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FINANCE_SERVICE_NAME = "FinanceService";

/** ===== SERVICE DEFINITION ===== */

export interface PartnerServiceClient {
  /** Partner đăng acc bán */

  createAccountSell(request: CreateAccountSellRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Partner cập nhật thông tin acc */

  updateAccountSell(request: UpdateAccountSellRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Partner xoá acc đã đăng */

  deleteAccountSell(request: DeleteAccountSellRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Lấy danh sách tất cả acc đang bán (user xem) */

  getAllActiveAccounts(request: Empty, metadata?: Metadata): Observable<ListAccountSellResponse>;

  /** Lấy danh sách acc theo partner (người bán xem) */

  getAccountsByPartner(request: GetAccountsByPartnerRequest, metadata?: Metadata): Observable<ListAccountSellResponse>;

  /** Lấy chi tiết 1 acc */

  getAccountById(request: GetAccountByIdRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Đánh dấu acc đã bán */

  markAccountAsSold(request: UpdateAccountStatusRequest, metadata?: Metadata): Observable<AccountSellResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface PartnerServiceController {
  /** Partner đăng acc bán */

  createAccountSell(request: CreateAccountSellRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Partner cập nhật thông tin acc */

  updateAccountSell(request: UpdateAccountSellRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Partner xoá acc đã đăng */

  deleteAccountSell(request: DeleteAccountSellRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Lấy danh sách tất cả acc đang bán (user xem) */

  getAllActiveAccounts(request: Empty, metadata?: Metadata): Observable<ListAccountSellResponse>;

  /** Lấy danh sách acc theo partner (người bán xem) */

  getAccountsByPartner(request: GetAccountsByPartnerRequest, metadata?: Metadata): Observable<ListAccountSellResponse>;

  /** Lấy chi tiết 1 acc */

  getAccountById(request: GetAccountByIdRequest, metadata?: Metadata): Observable<AccountSellResponse>;

  /** Đánh dấu acc đã bán */

  markAccountAsSold(request: UpdateAccountStatusRequest, metadata?: Metadata): Observable<AccountSellResponse>;
}

export function PartnerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createAccountSell",
      "updateAccountSell",
      "deleteAccountSell",
      "getAllActiveAccounts",
      "getAccountsByPartner",
      "getAccountById",
      "markAccountAsSold",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PartnerService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PartnerService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PARTNER_SERVICE_NAME = "PartnerService";
